# Generated by Django 4.1.3 on 2023-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhav_technicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
